import type { Sentence } from "@/types"

export const mockSentences: Record<string, Sentence[]> = {
  // ===== 牛津阅读树 Level 1 =====
  "gr_ot_01_lesson_01": [
    { id: "s_001", chinese: "我在公园里。", english: "I am at the park.", words_count: 5, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_01", words: [{ english: "I", chinese: "我", phonetic: "/aɪ/", pos: "代词" }, { english: "am", chinese: "是", phonetic: "/æm/", pos: "动词" }, { english: "at", chinese: "在", phonetic: "/æt/", pos: "介词" }, { english: "the", chinese: "这/那", phonetic: "/ðə/", pos: "冠词" }, { english: "park", chinese: "公园", phonetic: "/pɑːrk/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_002", chinese: "这只狗很大。", english: "The dog is big.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_01", words: [{ english: "The", chinese: "这", phonetic: "/ðə/", pos: "冠词" }, { english: "dog", chinese: "狗", phonetic: "/dɒɡ/", pos: "名词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "big", chinese: "大的", phonetic: "/bɪɡ/", pos: "形容词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_003", chinese: "我看见一只鸟。", english: "I see a bird.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_01", words: [{ english: "I", chinese: "我", phonetic: "/aɪ/", pos: "代词" }, { english: "see", chinese: "看见", phonetic: "/siː/", pos: "动词" }, { english: "a", chinese: "一个", phonetic: "/ə/", pos: "冠词" }, { english: "bird", chinese: "鸟", phonetic: "/bɜːrd/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_004", chinese: "它正在飞。", english: "It is flying.", words_count: 3, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_01", words: [{ english: "It", chinese: "它", phonetic: "/ɪt/", pos: "代词" }, { english: "is", chinese: "正在", phonetic: "/ɪz/", pos: "助动词" }, { english: "flying", chinese: "飞", phonetic: "/ˈflaɪ.ɪŋ/", pos: "动词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_005", chinese: "我喜欢这个公园。", english: "I like the park.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_01", words: [{ english: "I", chinese: "我", phonetic: "/aɪ/", pos: "代词" }, { english: "like", chinese: "喜欢", phonetic: "/laɪk/", pos: "动词" }, { english: "the", chinese: "这/那", phonetic: "/ðə/", pos: "冠词" }, { english: "park", chinese: "公园", phonetic: "/pɑːrk/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
  ],
  "gr_ot_01_lesson_02": [
    { id: "s_006", chinese: "妈妈在这里。", english: "Mum is here.", words_count: 3, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_02", words: [{ english: "Mum", chinese: "妈妈", phonetic: "/mʌm/", pos: "名词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "here", chinese: "在这里", phonetic: "/hɪər/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_007", chinese: "爸爸在门口。", english: "Dad is at the door.", words_count: 5, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_02", words: [{ english: "Dad", chinese: "爸爸", phonetic: "/dæd/", pos: "名词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "at", chinese: "在", phonetic: "/æt/", pos: "介词" }, { english: "the", chinese: "这/那", phonetic: "/ðə/", pos: "冠词" }, { english: "door", chinese: "门", phonetic: "/dɔːr/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_008", chinese: "快来看这个。", english: "Come and see this.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_02", words: [{ english: "Come", chinese: "来", phonetic: "/kʌm/", pos: "动词" }, { english: "and", chinese: "并且", phonetic: "/ænd/", pos: "连词" }, { english: "see", chinese: "看", phonetic: "/siː/", pos: "动词" }, { english: "this", chinese: "这个", phonetic: "/ðɪs/", pos: "代词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_009", chinese: "是一只猫。", english: "It is a cat.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_02", words: [{ english: "It", chinese: "它", phonetic: "/ɪt/", pos: "代词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "a", chinese: "一个", phonetic: "/ə/", pos: "冠词" }, { english: "cat", chinese: "猫", phonetic: "/kæt/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_010", chinese: "这只猫很小。", english: "The cat is little.", words_count: 4, category: "daily", difficulty: 1, tags: ["oxford"], lesson_id: "gr_ot_01_lesson_02", words: [{ english: "The", chinese: "这", phonetic: "/ðə/", pos: "冠词" }, { english: "cat", chinese: "猫", phonetic: "/kæt/", pos: "名词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "little", chinese: "小的", phonetic: "/ˈlɪt.əl/", pos: "形容词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
  ],
  // ===== 一年级英语上册 =====
  "ss_g1_01_lesson_01": [
    { id: "s_011", chinese: "早上好，同学们。", english: "Good morning, boys and girls.", words_count: 5, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_01", words: [{ english: "Good", chinese: "好", phonetic: "/ɡʊd/", pos: "形容词" }, { english: "morning", chinese: "早上", phonetic: "/ˈmɔːr.nɪŋ/", pos: "名词" }, { english: ",", chinese: null, phonetic: null, pos: "标点" }, { english: "boys", chinese: "男孩们", phonetic: "/bɔɪz/", pos: "名词" }, { english: "and", chinese: "和", phonetic: "/ænd/", pos: "连词" }, { english: "girls", chinese: "女孩们", phonetic: "/ɡɜːrlz/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_012", chinese: "请打开你的书。", english: "Open your book, please.", words_count: 4, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_01", words: [{ english: "Open", chinese: "打开", phonetic: "/ˈoʊ.pən/", pos: "动词" }, { english: "your", chinese: "你的", phonetic: "/jʊər/", pos: "代词" }, { english: "book", chinese: "书", phonetic: "/bʊk/", pos: "名词" }, { english: ",", chinese: null, phonetic: null, pos: "标点" }, { english: "please", chinese: "请", phonetic: "/pliːz/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_013", chinese: "你叫什么名字？", english: "What is your name?", words_count: 4, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_01", words: [{ english: "What", chinese: "什么", phonetic: "/wɒt/", pos: "代词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "your", chinese: "你的", phonetic: "/jʊər/", pos: "代词" }, { english: "name", chinese: "名字", phonetic: "/neɪm/", pos: "名词" }, { english: "?", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_014", chinese: "我叫刘明。", english: "My name is Liu Ming.", words_count: 5, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_01", words: [{ english: "My", chinese: "我的", phonetic: "/maɪ/", pos: "代词" }, { english: "name", chinese: "名字", phonetic: "/neɪm/", pos: "名词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "Liu", chinese: "刘", phonetic: "/ljuː/", pos: "名词" }, { english: "Ming", chinese: "明", phonetic: "/mɪŋ/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_015", chinese: "很高兴认识你。", english: "Nice to meet you.", words_count: 4, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_01", words: [{ english: "Nice", chinese: "好的", phonetic: "/naɪs/", pos: "形容词" }, { english: "to", chinese: null, phonetic: "/tə/", pos: "不定式" }, { english: "meet", chinese: "遇见", phonetic: "/miːt/", pos: "动词" }, { english: "you", chinese: "你", phonetic: "/juː/", pos: "代词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
  ],
  "ss_g1_01_lesson_02": [
    { id: "s_016", chinese: "这是一支铅笔。", english: "This is a pencil.", words_count: 4, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_02", words: [{ english: "This", chinese: "这", phonetic: "/ðɪs/", pos: "代词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "a", chinese: "一支", phonetic: "/ə/", pos: "冠词" }, { english: "pencil", chinese: "铅笔", phonetic: "/ˈpen.səl/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_017", chinese: "那是一块橡皮。", english: "That is an eraser.", words_count: 4, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_02", words: [{ english: "That", chinese: "那", phonetic: "/ðæt/", pos: "代词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "an", chinese: "一块", phonetic: "/æn/", pos: "冠词" }, { english: "eraser", chinese: "橡皮", phonetic: "/ɪˈreɪ.sər/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_018", chinese: "请把尺子给我。", english: "Give me a ruler, please.", words_count: 5, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_02", words: [{ english: "Give", chinese: "给", phonetic: "/ɡɪv/", pos: "动词" }, { english: "me", chinese: "我", phonetic: "/miː/", pos: "代词" }, { english: "a", chinese: "一把", phonetic: "/ə/", pos: "冠词" }, { english: "ruler", chinese: "尺子", phonetic: "/ˈruː.lər/", pos: "名词" }, { english: ",", chinese: null, phonetic: null, pos: "标点" }, { english: "please", chinese: "请", phonetic: "/pliːz/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_019", chinese: "把书合上。", english: "Close the book.", words_count: 3, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_02", words: [{ english: "Close", chinese: "合上", phonetic: "/kloʊz/", pos: "动词" }, { english: "the", chinese: "这", phonetic: "/ðə/", pos: "冠词" }, { english: "book", chinese: "书", phonetic: "/bʊk/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_020", chinese: "请坐下。", english: "Sit down, please.", words_count: 3, category: "daily", difficulty: 1, tags: ["school"], lesson_id: "ss_g1_01_lesson_02", words: [{ english: "Sit", chinese: "坐", phonetic: "/sɪt/", pos: "动词" }, { english: "down", chinese: "下", phonetic: "/daʊn/", pos: "副词" }, { english: ",", chinese: null, phonetic: null, pos: "标点" }, { english: "please", chinese: "请", phonetic: "/pliːz/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
  ],
  // ===== 中考英语完形填空 =====
  "ep_zk_01_lesson_01": [
    { id: "s_021", chinese: "他每天坐公交车上学。", english: "He goes to school by bus every day.", words_count: 8, category: "exam", difficulty: 2, tags: ["zhongkao"], lesson_id: "ep_zk_01_lesson_01", words: [{ english: "He", chinese: "他", phonetic: "/hiː/", pos: "代词" }, { english: "goes", chinese: "去", phonetic: "/ɡoʊz/", pos: "动词" }, { english: "to", chinese: null, phonetic: "/tə/", pos: "介词" }, { english: "school", chinese: "学校", phonetic: "/skuːl/", pos: "名词" }, { english: "by", chinese: "乘坐", phonetic: "/baɪ/", pos: "介词" }, { english: "bus", chinese: "公交车", phonetic: "/bʌs/", pos: "名词" }, { english: "every", chinese: "每个", phonetic: "/ˈev.ri/", pos: "形容词" }, { english: "day", chinese: "天", phonetic: "/deɪ/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_022", chinese: "学好英语对我们很重要。", english: "It is important for us to learn English well.", words_count: 10, category: "exam", difficulty: 2, tags: ["zhongkao"], lesson_id: "ep_zk_01_lesson_01", words: [{ english: "It", chinese: "它", phonetic: "/ɪt/", pos: "代词" }, { english: "is", chinese: "是", phonetic: "/ɪz/", pos: "动词" }, { english: "important", chinese: "重要的", phonetic: "/ɪmˈpɔːr.tənt/", pos: "形容词" }, { english: "for", chinese: "对于", phonetic: "/fɔːr/", pos: "介词" }, { english: "us", chinese: "我们", phonetic: "/ʌs/", pos: "代词" }, { english: "to", chinese: null, phonetic: "/tə/", pos: "不定式" }, { english: "learn", chinese: "学习", phonetic: "/lɜːrn/", pos: "动词" }, { english: "English", chinese: "英语", phonetic: "/ˈɪŋ.ɡlɪʃ/", pos: "名词" }, { english: "well", chinese: "好地", phonetic: "/wel/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_023", chinese: "她花费两个小时做作业。", english: "She spent two hours doing her homework.", words_count: 7, category: "exam", difficulty: 2, tags: ["zhongkao"], lesson_id: "ep_zk_01_lesson_01", words: [{ english: "She", chinese: "她", phonetic: "/ʃiː/", pos: "代词" }, { english: "spent", chinese: "花费", phonetic: "/spent/", pos: "动词" }, { english: "two", chinese: "二", phonetic: "/tuː/", pos: "数词" }, { english: "hours", chinese: "小时", phonetic: "/ˈaʊ.ərz/", pos: "名词" }, { english: "doing", chinese: "做", phonetic: "/ˈduː.ɪŋ/", pos: "动词" }, { english: "her", chinese: "她的", phonetic: "/hɜːr/", pos: "代词" }, { english: "homework", chinese: "作业", phonetic: "/ˈhoʊm.wɜːrk/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_024", chinese: "昨天老师告诉我们一个好消息。", english: "The teacher told us a piece of good news yesterday.", words_count: 10, category: "exam", difficulty: 2, tags: ["zhongkao"], lesson_id: "ep_zk_01_lesson_01", words: [{ english: "The", chinese: "这", phonetic: "/ðə/", pos: "冠词" }, { english: "teacher", chinese: "老师", phonetic: "/ˈtiː.tʃər/", pos: "名词" }, { english: "told", chinese: "告诉", phonetic: "/toʊld/", pos: "动词" }, { english: "us", chinese: "我们", phonetic: "/ʌs/", pos: "代词" }, { english: "a", chinese: "一个", phonetic: "/ə/", pos: "冠词" }, { english: "piece", chinese: "条", phonetic: "/piːs/", pos: "名词" }, { english: "of", chinese: "属于", phonetic: "/ʌv/", pos: "介词" }, { english: "good", chinese: "好的", phonetic: "/ɡʊd/", pos: "形容词" }, { english: "news", chinese: "消息", phonetic: "/nuːz/", pos: "名词" }, { english: "yesterday", chinese: "昨天", phonetic: "/ˈjes.tər.deɪ/", pos: "副词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: "s_025", chinese: "你能告诉我最近的医院怎么走吗？", english: "Could you tell me how to get to the nearest hospital?", words_count: 11, category: "exam", difficulty: 3, tags: ["zhongkao"], lesson_id: "ep_zk_01_lesson_01", words: [{ english: "Could", chinese: "能", phonetic: "/kʊd/", pos: "情态动词" }, { english: "you", chinese: "你", phonetic: "/juː/", pos: "代词" }, { english: "tell", chinese: "告诉", phonetic: "/tel/", pos: "动词" }, { english: "me", chinese: "我", phonetic: "/miː/", pos: "代词" }, { english: "how", chinese: "怎样", phonetic: "/haʊ/", pos: "副词" }, { english: "to", chinese: null, phonetic: "/tə/", pos: "不定式" }, { english: "get", chinese: "到达", phonetic: "/ɡet/", pos: "动词" }, { english: "to", chinese: "到", phonetic: "/tə/", pos: "介词" }, { english: "the", chinese: "这", phonetic: "/ðə/", pos: "冠词" }, { english: "nearest", chinese: "最近的", phonetic: "/ˈnɪr.ɪst/", pos: "形容词" }, { english: "hospital", chinese: "医院", phonetic: "/ˈhɒs.pɪ.təl/", pos: "名词" }, { english: "?", chinese: null, phonetic: null, pos: "标点" }] },
  ],
}

// Get all sentences for a given lesson (with fallback for lessons without data)
export function getMockSentencesByLesson(lessonId: string): Sentence[] {
  if (mockSentences[lessonId]) return mockSentences[lessonId]

  // Fallback: return a generic sentence for any lesson without explicit mock data
  return [
    { id: `fallback_${lessonId}_1`, chinese: "你好。", english: "Hello.", words_count: 1, category: "daily", difficulty: 1, tags: [], lesson_id: lessonId, words: [{ english: "Hello", chinese: "你好", phonetic: "/həˈloʊ/", pos: "感叹词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: `fallback_${lessonId}_2`, chinese: "谢谢。", english: "Thank you.", words_count: 2, category: "daily", difficulty: 1, tags: [], lesson_id: lessonId, words: [{ english: "Thank", chinese: "感谢", phonetic: "/θæŋk/", pos: "动词" }, { english: "you", chinese: "你", phonetic: "/juː/", pos: "代词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
    { id: `fallback_${lessonId}_3`, chinese: "你是我的朋友。", english: "You are my friend.", words_count: 4, category: "daily", difficulty: 1, tags: [], lesson_id: lessonId, words: [{ english: "You", chinese: "你", phonetic: "/juː/", pos: "代词" }, { english: "are", chinese: "是", phonetic: "/ɑːr/", pos: "动词" }, { english: "my", chinese: "我的", phonetic: "/maɪ/", pos: "代词" }, { english: "friend", chinese: "朋友", phonetic: "/frend/", pos: "名词" }, { english: ".", chinese: null, phonetic: null, pos: "标点" }] },
  ]
}
